package com.tolstykh.eatABurrita.ui.main

val BURRITO_FACTS: List<String> = listOf(
    "The word 'burrito' means 'little donkey' in Spanish.",
    "The world's largest burrito weighed 5,799 lbs and was made in California in 2010.",
    "A Mission-style burrito can contain over 1,200 calories.",
    "Burritos originated in Northern Mexico, not California.",
    "The foil-wrapped Mission burrito was popularized in San Francisco's Mission District in the 1960s.",
    "Juan Méndez is often credited with inventing the burrito in Ciudad Juárez around the 1940s.",
    "A traditional Mexican burrito uses only two or three ingredients - usually beans, meat, and cheese.",
    "The wet burrito (smothered in sauce) was invented in Michigan, not Mexico.",
    "California-style burritos frequently include french fries as a filling.",
    "Burritos are not traditionally served in most regions of Mexico - they're a northern specialty.",
    "The breakfast burrito is thought to have been invented in Santa Fe, New Mexico in 1975.",
    "A typical flour tortilla for a burrito can stretch up to 12 inches in diameter.",
    "Flour tortillas became popular in northern Mexico because wheat grew better there than corn.",
    "The rice-and-beans combo in burritos forms a complete protein on its own.",
    "Chipotle's burritos weigh about 1.3 lbs on average when fully loaded.",
    "The 'burrito bowl' became popular after Chipotle added it in 2004.",
    "Guacamole gets its name from the Nahuatl word 'ahuacamolli' meaning avocado sauce.",
    "One avocado tree can produce up to 400 avocados per year for guacamole.",
    "Mexico produces about 30% of the world's avocado supply.",
    "Jalapeños are named after Xalapa, the capital city of Veracruz, Mexico.",
    "Sour cream was introduced to Mexican-American food in the 20th century - it's not traditional.",
    "Pinto beans get their name from the Spanish word for 'painted' due to their mottled appearance.",
    "Black beans are higher in antioxidants than most other bean varieties.",
    "Carne asada translates literally to 'grilled meat' in Spanish.",
    "Al pastor meat is cooked on a vertical spit inspired by Lebanese shawarma immigrants to Mexico.",
    "The trompo (al pastor spit) was introduced to Mexico by Lebanese immigrants in the 1930s.",
    "Carnitas means 'little meats' and is traditionally made by slow-braising pork in lard.",
    "Salsa translates simply to 'sauce' in Spanish.",
    "Pico de gallo literally means 'rooster's beak' - the origin of the name is debated.",
    "Cilantro is one of the most genetically polarizing foods: love or hate it is partly determined by genes.",
    "Cumin, a key burrito spice, was used in ancient Egypt over 5,000 years ago.",
    "Mexican oregano is a different plant than Mediterranean oregano and has a stronger flavor.",
    "Lime juice in guacamole prevents oxidation - that's why it stays green longer.",
    "Tortillas were first made by Mesoamerican civilizations over 10,000 years ago.",
    "The Aztecs used corn tortillas as both food and utensil - no plates needed.",
    "Flour tortillas were invented after Spanish colonizers introduced wheat to the Americas.",
    "A properly made burrito should be sealed by folding, not pinching, so it holds its shape.",
    "The 'smash' style of sealing a burrito uses a flat press to make it grill-friendly.",
    "Burritos were largely unknown in Mexico City until American fast-food chains spread them there.",
    "San Francisco's Mission District burritos are famously larger than most - up to 1 lb.",
    "The first Chipotle restaurant opened in Denver, Colorado in 1993.",
    "Taco Bell introduced the 'Bell Beefer' burrito-style item in the 1970s.",
    "Del Taco was founded in 1964, predating Taco Bell's wider national expansion.",
    "The burrito emoji 🌯 was added to Unicode in 2015.",
    "Americans eat an estimated 3.5 billion burritos per year.",
    "February 5th is National Burrito Day in the United States.",
    "A burrito rolling competition is held annually at the Indio International Tamale Festival.",
    "Burritos are one of the top five most ordered foods on delivery apps in the US.",
    "Queso blanco used in burritos is typically made from Oaxacan-style melting cheeses.",
    "Monterey Jack cheese was developed by David Jacks, a Scottish-born California dairy farmer.",
    "Pepper jack cheese was invented in California by combining Monterey Jack with spicy peppers.",
    "Hot sauce sales in the US have grown by over 150% since 2000.",
    "Tabasco sauce has been made on Avery Island, Louisiana since 1868.",
    "Sriracha sauce was first produced in the US by David Tran, a Vietnamese immigrant, in 1980.",
    "Rice in burritos is typically cooked using a 'Mexican rice' technique - toasted then simmered in broth.",
    "Tomatoes were brought from the Americas to Europe by Spanish explorers in the 1500s.",
    "Bell peppers are technically a fruit - and are botanically related to jalapeños and serranos.",
    "Corn was domesticated in Mexico about 9,000 years ago from a wild grass called teosinte.",
    "The US grows more corn than any other country - much of it used for animal feed, not tortillas.",
    "One pound of dried beans yields about 2.5 pounds of cooked beans - great burrito math.",
    "A standard Mission burrito contains roughly 70-80g of protein when made with chicken or steak.",
)
